# Generated by Django 5.2.5 on 2025-08-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mode',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('banned', 'Banned')], default='created', max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=256, unique_for_date=True),
        ),
    ]
