# Generated by Django 5.2.5 on 2025-08-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_post_mode_post_status_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tags', to='weblog.tag'),
        ),
    ]
