# Generated by Django 5.2.5 on 2025-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='born_date',
            field=models.DateField(null=True),
        ),
    ]
