# Generated by Django 5.2.5 on 2025-09-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_born_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1, max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('user', 'User'), ('member', 'Member'), ('vip', 'VIP'), ('sponsor', 'Sponsor')], default='user', max_length=8),
        ),
    ]
