# Generated by Django 5.2.5 on 2025-09-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_level_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
