# Generated by Django 5.2.5 on 2025-08-23 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=128)),
                ('text', models.TextField(max_length=1024)),
                ('type', models.CharField(choices=[('objection', 'Objection'), ('suggestion', 'Suggestion'), ('appreciation', 'Appreciation'), ('user_report', 'User Report'), ('bug_report', 'Bug Report')], max_length=64)),
                ('answer', models.TextField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answered', models.DateTimeField(auto_now=True)),
                ('is_answer', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
